server:
  port: 8080

spring:
  application:
    name: distributed-hash-table

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

dht:
  replication-factor: 3
  virtual-nodes: 150
  initial-nodes:
    - id: node1
      host: localhost
      port: 8001
    - id: node2
      host: localhost
      port: 8002
    - id: node3
      host: localhost
      port: 8003

logging:
  level:
    com.dht: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"